//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderline
    {
        public int Order_idOrder { get; set; }
        public int Product_idProduct { get; set; }
        public int idSpecialOffer { get; set; }
        public int Quantity { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
        public virtual specialoffer specialoffer { get; set; }
    }
}
