//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storedbEntities : DbContext
    {
        public storedbEntities()
            : base("name=storedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderline> orderline { get; set; }
        public virtual DbSet<paymenttype> paymenttype { get; set; }
        public virtual DbSet<pendingproduct> pendingproduct { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<producttype> producttype { get; set; }
        public virtual DbSet<specialoffer> specialoffer { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<usercomment> usercomment { get; set; }
    }
}
